import { useState } from 'react'

/**
 * Parse "Evidence used: E1, E3, E5" from the end of insight text.
 * Returns { text, citedIds } where text has the evidence line removed.
 */
function parseEvidenceCitations(text) {
  if (!text) return { text: '', citedIds: [] }
  const match = text.match(/Evidence used:\s*((?:E\d+(?:,\s*)?)+)\s*\.?\s*$/)
  if (!match) return { text, citedIds: [] }
  const ids = match[1].split(/,\s*/).map(s => s.trim()).filter(Boolean)
  return { text: text.slice(0, match.index).trim(), citedIds: ids }
}

function EvidenceThumbnail({ ev, isCited }) {
  const [hovered, setHovered] = useState(false)
  const borderClass = ev.label === 'best' ? 'best' : ev.label === 'worst' ? 'worst' : 'transition'

  return (
    <div
      className={`evidence-thumb ${borderClass} ${isCited ? 'cited' : ''}`}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {ev.thumbnail_url && (
        <img src={ev.thumbnail_url} alt={`Evidence ${ev.id}`} loading="lazy" />
      )}
      <span className="evidence-label">{ev.id}</span>

      {hovered && (
        <div className="evidence-tooltip">
          {ev.thumbnail_url && (
            <img
              src={ev.thumbnail_url}
              alt={`${ev.id} enlarged`}
              style={{ width: '100%', aspectRatio: '16/9', objectFit: 'cover', marginBottom: '8px' }}
            />
          )}
          <div style={{ fontSize: '10px', color: 'var(--accent-green)', fontWeight: 600, marginBottom: '4px' }}>
            {ev.id} / {ev.label}
          </div>
          <div style={{ fontSize: '11px', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
            {ev.description}
          </div>
          {ev.visual_tags && ev.visual_tags.length > 0 && (
            <div style={{ marginTop: '6px', display: 'flex', flexWrap: 'wrap', gap: '3px' }}>
              {ev.visual_tags.map(tag => (
                <span key={tag} style={{
                  fontSize: '8px',
                  padding: '1px 4px',
                  background: 'rgba(245,240,232,0.08)',
                  color: 'var(--text-muted)',
                  letterSpacing: '0.04em',
                }}>{tag}</span>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

/**
 * InsightPanel — Displays LLM-generated walkability insight with scene evidence thumbnails.
 * Shows loading, error, and cached states.
 */
export default function InsightPanel({ insight, model, cached, loading, error, sceneEvidence }) {
  if (error) {
    return (
      <div className="card" style={{
        padding: '24px',
        borderLeft: '3px solid var(--accent-orange)',
      }}>
        <div style={{
          fontSize: '11px',
          color: 'var(--accent-orange)',
          textTransform: 'uppercase',
          letterSpacing: '0.08em',
          marginBottom: '8px',
          fontWeight: 500,
        }}>
          Insight Unavailable
        </div>
        <div style={{
          fontSize: '13px',
          color: 'var(--text-muted)',
          lineHeight: 1.7,
        }}>
          Could not generate AI insight. The analytics data above is still accurate.
        </div>
      </div>
    )
  }

  const { text: insightText, citedIds } = parseEvidenceCitations(insight)

  return (
    <div className="card" style={{
      padding: '24px',
      borderLeft: '3px solid var(--accent-green)',
    }}>
      <div style={{
        fontSize: '11px',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
        color: 'var(--accent-green)',
        marginBottom: '12px',
        fontWeight: 500,
      }}>
        AI Insight
      </div>

      {loading ? (
        <div style={{
          fontSize: '13px',
          color: 'var(--text-muted)',
          fontStyle: 'italic',
          lineHeight: 1.7,
        }}>
          Analyzing street data...
        </div>
      ) : (
        <>
          <p style={{
            fontSize: '14px',
            lineHeight: 1.8,
            color: 'var(--text-secondary)',
            fontWeight: 300,
            margin: 0,
          }}>
            {insightText}
          </p>

          {sceneEvidence && sceneEvidence.length > 0 && (
            <div className="evidence-strip">
              {sceneEvidence.map(ev => (
                <EvidenceThumbnail
                  key={ev.id}
                  ev={ev}
                  isCited={citedIds.includes(ev.id)}
                />
              ))}
            </div>
          )}

          <div style={{
            fontSize: '9px',
            color: 'var(--text-muted)',
            marginTop: '12px',
            letterSpacing: '0.06em',
          }}>
            Generated by {model}{cached ? ' (cached)' : ''}
            {citedIds.length > 0 && (
              <span style={{ marginLeft: '8px' }}>
                Evidence: {citedIds.join(', ')}
              </span>
            )}
          </div>
        </>
      )}
    </div>
  )
}
