/**
 * InsightPanel — Displays LLM-generated walkability insight.
 * Shows loading, error, and cached states.
 */
export default function InsightPanel({ insight, model, cached, loading, error }) {
  if (error) {
    return (
      <div className="card" style={{
        padding: '24px',
        borderLeft: '3px solid var(--accent-orange)',
      }}>
        <div style={{
          fontSize: '11px',
          color: 'var(--accent-orange)',
          textTransform: 'uppercase',
          letterSpacing: '0.08em',
          marginBottom: '8px',
          fontWeight: 500,
        }}>
          Insight Unavailable
        </div>
        <div style={{
          fontSize: '13px',
          color: 'var(--text-muted)',
          lineHeight: 1.7,
        }}>
          Could not generate AI insight. The analytics data above is still accurate.
        </div>
      </div>
    )
  }

  return (
    <div className="card" style={{
      padding: '24px',
      borderLeft: '3px solid var(--accent-green)',
    }}>
      <div style={{
        fontSize: '11px',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
        color: 'var(--accent-green)',
        marginBottom: '12px',
        fontWeight: 500,
      }}>
        AI Insight
      </div>

      {loading ? (
        <div style={{
          fontSize: '13px',
          color: 'var(--text-muted)',
          fontStyle: 'italic',
          lineHeight: 1.7,
        }}>
          Analyzing street data...
        </div>
      ) : (
        <>
          <p style={{
            fontSize: '14px',
            lineHeight: 1.8,
            color: 'var(--text-secondary)',
            fontWeight: 300,
            margin: 0,
          }}>
            {insight}
          </p>
          <div style={{
            fontSize: '9px',
            color: 'var(--text-muted)',
            marginTop: '12px',
            letterSpacing: '0.06em',
          }}>
            Generated by {model}{cached ? ' (cached)' : ''}
          </div>
        </>
      )}
    </div>
  )
}
